version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.integration:spring-integration-http
    versions:
    - 5.4.3
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.springframework.security:spring-security-web
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
