---
swagger: '2.0'
info:
  version: 1.0.0
  title: ATM Locator 
  description: |
    #### ATM Locator is an internet portal that acts as an interface to actual locations of ATM belonging to ING bank.

schemes:
  - http
host: localhost:8080
basePath: /atm-locator
paths:
  /login:
    post:
      tags:
        - Sign in    
      responses:
        200:
          description: Sign in via POST request
      parameters:
        - name: username
          in: formData
          description: User name
          type: string
        - name: password
          in: formData
          description: Password
          type: string
        - name: _csrf
          in: formData
          description: Token
          type: string
  /atm/{bank}/raw:
    parameters:
      - name: bank
        in: path
        description: Bank
        type: string
        required: true
      - name: city
        in: query
        description: City
        type: string
        required: false
    get:
      tags:
        - Raw    
      responses:
        200:
          description: Search nearest ING ATM by city. The response is in JSON original format
  /atm/{bank}/search:
    parameters:
      - name: bank
        in: path
        description: Bank
        type: string
        required: true
      - name: city
        in: query
        description: City
        type: string
        required: false
    get:
      tags:
        - Simple    
      responses:
        200:
          description: Search nearest ING ATM by city. The response is in JSON simplified format. It only contains number of values - street, post code, city 
          
